# Warm Up

Write a function to return the number of even integers in a given array.  

Hint: the % "modulo" operator computes the remainder, e.g. 5 % 2 is 1. 

You may assume the user has inputted a list of numbers. (So there is no need to check type.) 

In [6]:
def count_evens(input_list): 
    if len(input_list)==0: 
        return 0
    else: 
        #Let n = count of total even numbers
        n = 0
        for item in input_list: 
            if item%2 == 0: 
                n += 1
        return n

In [7]:
print(count_evens([1, 1, 2, 5, 2])) #Should return 2
print(count_evens([2, 2, 0])) #Should return 3
print(count_evens([1, 3, 5])) #Should return 0

2
3
0


# Indirect Indexing

Let's say you're a broke UCLA student. To earn enough money to eat the Poke bowls for lunch, you pick up a side job at Murphy Hall, handling their student directory. The directory is set up such that each inner list comprises of: [Name, ID Number, Total Units]. 
    
First write a function that returns the person's name when you input their ID number.

In [1]:
Directory = [['Latoyia', 20394, 613], ['Antony', 12350, 630], ['Stephanie', 20935, 123], ['Selma', 103512, 521],
             ['Scarlet', 10293, 192], ['Song', 10925, 452], ['Laci', 109564, 632], ['Rocky', 109323, 401], 
             ['Kristin', 149506, 320], ['Jovita', 20961, 531], ['Cossondra', 23093, 349]]

In [4]:
directory_dict = {Directory[i][1]: Directory[i][0] for i in range(len(Directory))}
print(directory_dict)

{20394: 'Latoyia', 12350: 'Antony', 20935: 'Stephanie', 103512: 'Selma', 10293: 'Scarlet', 10925: 'Song', 109564: 'Laci', 109323: 'Rocky', 149506: 'Kristin', 20961: 'Jovita', 23093: 'Cossondra'}


In [6]:
def recallStudentName(ID): 
    return(directory_dict[ID])

recallStudentName(12350)

'Antony'

Now assume you have a list called Names. Write a function that takes in the person's name and returns the index that their name is located.

In [8]:
Names = ['Song', 'Latoyia', 'Kristin', 'Antony', 'Stephanie', 
         'Scarlet', 'Laci', 'Cassondra', 'Jovita', 'Selma', 'Rocky']

In [11]:
index_dict = {Names[i]:i for i in range(len(Names))}

def findIndex(name): 
    return index_dict[name]

In [12]:
print(findIndex("Song")) #should return 0 (as Song is located first in the Names list)

0


Now for the final part, write a function that takes in a person's ID number and returns the index at which their name is located on the "Names" list.

In [13]:
def findStudent(ID):
    return findIndex(recallStudentName(ID))

In [14]:
findStudent(12350)

3

# Text Processing & Data Cleaning

Write a function to return the unique words in the following paragraph. Count contractions as their expanded form (i.e., 'can't' is effectively two words: 'can' and 'not'). Punctuation should not be counted as words, nor should spaces.  

Hint: find a way to remove white spaces, punctuation, and symbols first. (Manually removing does not count! In this case, the text you are working with is relatively short, but in real life, you will be working with an unreadable amount of text) This can be done easily using with regular expressions (read more about it: https://docs.python.org/3/howto/regex.html), but if you don't want to venture down that road, you may find the replace() attribute of strings particularly helpful. 

In [23]:
paragraph = 'Python, from the Greek word, is a genus of nonvenomous Pythonidae  [2] \
found in Africa and Asia. Until recently, seven extant species were recognised;[2] \
however, three subspecies have      been promoted and a new species recognised. A member \
of this genus, P. reticulatus, is among the longest snake species and extant reptiles \
in the world. In Africa, members of the genus are found in the tropics south of the Sahara, \
but not in the extreme south-western tip of southern Africa (Western Cape) or in Madagascar. \
In Asia, they are found from Bangladesh, Nepal, India, Pakistan, and Sri Lanka, including the \
Nicobar   Islands, through Myanmar, east to Indochina, southern China, Hong Kong and Hainan, as \
well as in the Malayan region of Indonesia     and the Philippines.[1] Some suggest that P. molurus \
and P. sebae have the potential to be problematic invasive species in South Florida.[3] The\
United States Department of Agriculture reports that only Python bivittatus is an invasive species \
in the United States.[4] In early 2016, after a culling operation yielded 106 of the animals,\
Everglades park officials suggested  that "thousands" may live within the park, and that the species \
has been breeding there for some years. More recent data suggest that these pythons wouldn\'t \
withstand winter climates north of  Florida, contradicting previous research suggesting a more \
significant geographic potential range.[5][6]'

In [24]:
#Let's begin by removing punctuation: 
remove_punctuation = [',', '[', ']', '(', ')', '"', ';', '.']
for ch in remove_punctuation: 
    paragraph = paragraph.replace(ch, ' ')

print(paragraph)

Python  from the Greek word  is a genus of nonvenomous Pythonidae   2  found in Africa and Asia  Until recently  seven extant species were recognised  2  however  three subspecies have      been promoted and a new species recognised  A memberof this genus  P  reticulatus  is among the longest snake species and extant reptiles in the world  In Africa  members of the genus are found in the tropics south of the Sahara but not in the extreme south-western tip of southern Africa  Western Cape  or in Madagascar In Asia  they are found from Bangladesh  Nepal  India  Pakistan  and Sri Lanka  including theNicobar   Islands  through Myanmar  east to Indochina  southern China  Hong Kong and Hainan  as well as in the Malayan region of Indonesia     and the Philippines  1  Some suggest that P  molurusand P  sebae have the potential to be problematic invasive species in South Florida  3  TheUnited States Department of Agriculture reports that only Python bivittatus is an invasive species in the Unit

**A note on this method to remove punctuation and symbols:**

This works reasonably well, and is computationally fast! However, if we have a LOT of data, then identifying the symbols we want to remove will be much more difficult, in which case, I would highly recommend using regular expressions. 

In [22]:
set(paragraph.split())

{'1',
 '106',
 '2',
 '2016',
 '3',
 '4',
 '5',
 '6',
 'A',
 'Africa',
 'Agriculture',
 'Asia',
 'Bangladesh',
 'Cape',
 'China',
 'Department',
 'Everglades',
 'Florida',
 'Greek',
 'Hainan',
 'Hong',
 'In',
 'India',
 'Indochina',
 'Indonesia',
 'Islands',
 'Kong',
 'Lanka',
 'Madagascar',
 'Malayan',
 'More',
 'Myanmar',
 'Nepal',
 'P',
 'Pakistan',
 'Philippines',
 'Python',
 'Pythonidae',
 'Sahara',
 'Some',
 'South',
 'Sri',
 'States',
 'TheUnited',
 'United',
 'Until',
 'Western',
 'a',
 'after',
 'among',
 'an',
 'and',
 'animals',
 'are',
 'as',
 'be',
 'been',
 'bivittatus',
 'breeding',
 'but',
 'climates',
 'contradicting',
 'culling',
 'data',
 'early',
 'east',
 'extant',
 'extreme',
 'for',
 'found',
 'from',
 'genus',
 'geographic',
 'has',
 'have',
 'however',
 'in',
 'including',
 'invasive',
 'is',
 'live',
 'longest',
 'may',
 'memberof',
 'members',
 'molurusand',
 'more',
 'new',
 'nonvenomous',
 'north',
 'not',
 'of',
 'officials',
 'only',
 'operation',
 'or',
 

In [25]:
def returnUniqueWords(text): 
    remove_punctuation = [',', '[', ']', '(', ')', '"', ';', '.']
    for ch in remove_punctuation: 
        paragraph = paragraph.replace(ch, ' ')
    return set(paragraph.split())

Write a function that returns the total number of times a word appears in a given body of text. Your function should be robust enough such that if you input a contraction, it will count the total number of instances the contraction appears, as well as the separate words (i.e., 'haven't' and 'have not' both appear in the text, this would mean if we input 'haven't' into our function, it will return 2 counts). Make it such that your function is not case sensitive (so "Hello" and "hello" are counted as the same word). If the word you input into the function does not exist in the given body of text, return zero. Try it on the paragraph above. 

In [ ]:
def term_occurence(term, text): 

# Numpy Exercises

I've provided two very basic Numpy exercises. More can be found [**here**](https://github.com/rougier/numpy-100/blob/master/100%20Numpy%20exercises%20no%20solution.ipynb).

Create a 3x3 matrix with values ranging from 0 to 8 

In [26]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Create a 10x10 array with random values and find the minimum and maximum values

In [29]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0199996264776 0.999704650477
