In [1]:
import numpy as np

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.ones(3)

array([1., 1., 1.])

In [4]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.random.random((3,2))

array([[0.05679997, 0.18869259],
       [0.54477693, 0.06083508],
       [0.22455093, 0.98166556]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
x1 = np.random.random((3,3))
x2 = np.eye(3) 

In [16]:
print(x1)

[[0.47042761 0.46195306 0.50528178]
 [0.90051018 0.59890083 0.43867792]
 [0.69548282 0.73487419 0.20710831]]


In [17]:
print(x2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
x1*x2

array([[0.47042761, 0.        , 0.        ],
       [0.        , 0.59890083, 0.        ],
       [0.        , 0.        , 0.20710831]])

In [11]:
np.dot(x1, x2)

array([[0.65537097, 0.83412301, 0.0042226 ],
       [0.4582703 , 0.15352072, 0.54074013],
       [0.54829457, 0.86234986, 0.47022174]])

In [ ]:
#Create a 3x3 matrix with values ranging from 0 to 8 
np.array([[0,1,2],
         [3,4,5],
         [6,7,8]])

In [20]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
#Create a 10x10 array with random values and find the minimum and maximum values 
dimensions = (10,10)
random_matrix = np.random.random(dimensions)
print(random_matrix)

[[0.07044954 0.69445068 0.25460301 0.5824096  0.84756213 0.62699109
  0.98737999 0.53378431 0.83379961 0.17246227]
 [0.63627127 0.39851106 0.94501358 0.50419609 0.78126011 0.94944717
  0.13149142 0.53969884 0.71600645 0.89327701]
 [0.62573828 0.35874996 0.91525543 0.80514458 0.95663663 0.70592594
  0.4267503  0.96647394 0.28756853 0.61819088]
 [0.65195448 0.08778569 0.44883504 0.28645601 0.64312956 0.46406421
  0.68243589 0.4528623  0.00383924 0.91885906]
 [0.47990042 0.44382378 0.51242675 0.94966538 0.64234138 0.33975528
  0.78581786 0.84146439 0.42420129 0.56281412]
 [0.58526406 0.74001523 0.31758527 0.14890895 0.23412315 0.54552667
  0.53328649 0.76028095 0.89580838 0.16707608]
 [0.57644513 0.37095031 0.09320685 0.05285393 0.6398674  0.63884181
  0.7297099  0.37578652 0.79304143 0.03580374]
 [0.77570501 0.79552211 0.88997675 0.57035007 0.90157035 0.81414341
  0.81219682 0.86527913 0.49695927 0.13597905]
 [0.03606227 0.1946394  0.7304718  0.21773602 0.23869684 0.00438052
  0.26642785

In [24]:
np.min(random_matrix)

0.0038392441459838

In [25]:
np.max(random_matrix)

0.9873799929139069

In [28]:
#Create a null vector (vector of all zeroes) of size 10 but the 5th value is 1 
zero_vector = np.zeros(10)
print(zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
zero_vector[4] = 1

In [30]:
print(zero_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [31]:
#Generate a random vector of size 30 and find the mean 
random_vector = np.random.random(30)
print(random_vector)

[0.56035431 0.67836937 0.12283981 0.51324835 0.44264907 0.76348384
 0.9385935  0.9708331  0.4257209  0.83762013 0.55175202 0.52071549
 0.83671031 0.4430104  0.5449002  0.25720252 0.29178822 0.83766385
 0.48381775 0.18149788 0.14304326 0.83807848 0.93106961 0.03832106
 0.88817991 0.08409626 0.5477395  0.53964646 0.79826557 0.48559971]


In [32]:
np.mean(random_vector)

0.5498936949715961

In [33]:
##Indexing Example 

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
print(arr[5:8])

[5 6 7]


In [35]:
arr[5:8] = 12

In [36]:
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [37]:
arr_slice = arr[5:8]

In [38]:
print(arr_slice)

[12 12 12]


In [39]:
arr_slice[1] = 12345

In [40]:
print(arr_slice)

[   12 12345    12]


In [41]:
print(arr)

[    0     1     2     3     4    12 12345    12     8     9]


In [42]:
arr_slice = 64

In [43]:
print(arr_slice)

64


In [44]:
arr_slice = arr[5:8]
arr_slice[:] = 64
print(arr_slice)

[64 64 64]


In [45]:
arr = np.array([[0,1,2],
         [3,4,5],
         [6,7,8]])

In [46]:
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [47]:
arr[:,:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [48]:
arr[1,:2]

array([3, 4])

In [50]:
# Boolean Indexing 
data = np.random.random((7, 4))*10-5
print(data)

[[-2.45766514 -4.09985832  2.60157425 -3.03675354]
 [-0.43381333  0.06078676  3.61510806  4.16635733]
 [-3.00454358 -0.50443501  2.10733353  2.79911562]
 [-3.28145416  2.23929167 -4.69245175  4.49849828]
 [-1.39527554  4.88622043  2.51023908 -3.52355642]
 [ 4.8153081  -2.49963635 -3.07209171 -2.20495666]
 [-3.83639681  3.54977846 -1.32987356 -0.96288877]]


In [51]:
data < 0

array([[ True,  True, False,  True],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True, False,  True, False],
       [ True, False, False,  True],
       [False,  True,  True,  True],
       [ True, False,  True,  True]])

In [53]:
data[data < 0] = 0

In [54]:
data

array([[0.        , 0.        , 2.60157425, 0.        ],
       [0.        , 0.06078676, 3.61510806, 4.16635733],
       [0.        , 0.        , 2.10733353, 2.79911562],
       [0.        , 2.23929167, 0.        , 4.49849828],
       [0.        , 4.88622043, 2.51023908, 0.        ],
       [4.8153081 , 0.        , 0.        , 0.        ],
       [0.        , 3.54977846, 0.        , 0.        ]])

In [55]:
import pandas as pd

In [58]:
data = {
'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 
'year': [2000, 2001, 2002, 2001, 2002],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9]
} 
frame = pd.DataFrame(data) 
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [57]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [59]:
frame['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object

In [60]:
frame.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object

In [64]:
frame.iloc[0]

state    Ohio
year     2000
pop       1.5
Name: 0, dtype: object

In [65]:
data = pd.DataFrame(
    np.arange(16).reshape((4, 4)), 
    index=['Ohio', 'Colorado', 'Utah', 'New York'], 
           columns=['one', 'two', 'three', 'four']) 
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [66]:
np.arange(16).reshape((4, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
data['three'][0]

2

In [70]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [71]:
data.drop(['four'], axis=1)

one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [72]:
frame = pd.DataFrame(
    np.random.randn(4, 3), 
    columns=list('bde'), 
    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.519052 -0.818627 -1.089173
Ohio    1.210780  1.785449 -0.101619
Texas   0.514474 -0.010886  0.832586
Oregon -1.181335 -0.608964  1.034399

In [73]:
np.abs(frame)

b         d         e
Utah    0.519052  0.818627  1.089173
Ohio    1.210780  1.785449  0.101619
Texas   0.514474  0.010886  0.832586
Oregon  1.181335  0.608964  1.034399